### ISSUE TITLE
Refactoring stats page

### ISSUE THREAD

**Issue by theflucs** [DevLeonardoCommunity/github-stats#102]
### Describe the feature

Refactor the stats page:
separate the filters from the visualisation
create utils functions to avoid repetitions

### It should be implemented because

Making the code cleaner will increase readability and efficiency.
It will also be easier to find and fix bugs or vulnerabilities in the code.

### Additional context

To start off I would make a single `ReposFilters` component that groups all the filters code (without creating a new component for each filter). It cleans up a bit the stats page without being too verbose and leaves room for more refactoring if needed.
@Balastrong how do you see it?

### Would you like to work on this issue?

Yes

**Comment by Balastrong** [comment]
Sounds like a good plan, let's start moving stuff away from that huge page :D
