### ISSUE TITLE
Wrong icon in open Pull Requests

### ISSUE THREAD

**Issue by Balastrong** [DevLeonardoCommunity/github-stats#110]
### Describe your issue

Here on line 83 we show the `GoIssueOpened` icon which renders the open issue icon. I think there should be a dedicated icon for open pull requests.

https://github.com/DevLeonardoCommunity/github-stats/blob/d71c03f97f12354e7c82b5ae5ca7c50c0cb28056/src/components/RepositoryContributionsCard.tsx#L78-L84

### Steps to reproduce

1. Login
2. Go to the stats page
3. Have an open PR in your cards

### Put here any screenshots or videos (optional)

![image](https://github.com/DevLeonardoCommunity/github-stats/assets/7253929/48c2b3f3-952c-46a5-94c4-68a79ee3865a)

### Would you like to work on this issue?

None

**Comment by priyankarpal** [comment]
It should have the same icon as the merged PR, but the color should be green. What do you think?

**Comment by Balastrong** [comment]
There should be an Icon for open PRs too if I'm not mistaken

**Comment by K1ethoang** [comment]
You want to like that?

![image](https://github.com/DevLeonardoCommunity/github-stats/assets/88199151/d364d315-e2a7-4c88-b0fb-4204057bbd14)

**Comment by K1ethoang** [comment]
#114

**Comment by Balastrong** [comment]
Done in #114
