### ISSUE TITLE
bug: profile card should have more width 

### ISSUE THREAD

**Issue by priyankarpal** [DevLeonardoCommunity/github-stats#112]
### Describe your issue

To improve the user experience, the profile card should be wider

### Steps to reproduce

go to profile page & see the card width 

## before
![before](https://github.com/DevLeonardoCommunity/github-stats/assets/88102392/583df1cc-47d7-4a5c-abb0-aea3d650a499)
## After
![after](https://github.com/DevLeonardoCommunity/github-stats/assets/88102392/180031f0-0923-49eb-b135-5d58836dec3f)

### Would you like to work on this issue?

Yes

**Comment by priyankarpal** [comment]
it's responsive

**Comment by Balastrong** [comment]
Good idea, go for it! :)
