### ISSUE TITLE
Addition of a Docker File

### ISSUE THREAD

**Issue by Tanuj1718** [DevLeonardoCommunity/github-stats#115]
### Describe the feature

Currently docker is used almost in every repository whether the codebase is small or large. There should be a docker file for this repository also.

### It should be implemented because

It will allow contributors to work flawlessly because when they will install packages or dependencies, they will not face any warnings or error. Currently the node version used in this repository is old and when a new contributor will install the dependencies , he/she may can face difficulties.

### Additional context

Issue while installing dependencies:

![Image](https://github.com/user-attachments/assets/c4497462-02cc-4d88-846d-cc483dec3e28)

### Would you like to work on this issue?

Yes

**Comment by Tanuj1718** [comment]
@Balastrong can you please assign it to me? I will try my best to work on this.

**Comment by Balastrong** [comment]
There's plenty of tool to manage npm versions, I think adding an extra layer with docker only for that is overkill.

In that specific case we can allow higher node versions in package.json and it should cover this situation, do you want to take care of that?

**Comment by Tanuj1718** [comment]
Although I am new in docker but I think it's not just about npm versions. There are many other advantages when this codebase grow or move in the production.

**Comment by Balastrong** [comment]
At the current state running npm install is enough to have the project running, we'll think about adding docker when we'll have problems that can be solved with docker then :)
