### ISSUE TITLE
Card view adds horizontal scroll

### ISSUE THREAD

**Issue by Balastrong** [DevLeonardoCommunity/github-stats#86]
### Describe your issue

There's an horizontal scroll in the card view that shouldn't be there

### Steps to reproduce

1. Login
2. Go to the stats page
3. (select the cards view)

### What was the expected result?

No horizontal scroll

### Extra fields

- [X] I have used the search function to check if an issue already exists
- [ ] I'd like to work on this issue

**Comment by priyankarpal** [comment]
assign me I want to work on this issue

**Comment by Balastrong** [comment]
Sure :)

**Comment by priyankarpal** [comment]
completed @Balastrong please close this issue
