### ISSUE TITLE
ThemeSelector icon color not changing on dark mode

### ISSUE THREAD

**Issue by theflucs** [DevLeonardoCommunity/github-stats#90]
### Describe your issue

When dark mode is selected the icons remain black so they are not clearly visible on the dark background.

### Steps to reproduce

Switch to dark theme from header navbar

### What was the expected result?

I expect the icons to change their color to white so to be clearly visible

### Put here any screenshots or videos (optional)

![Screenshot 2024-01-18 at 10 01 43](https://github.com/DevLeonardoCommunity/github-stats/assets/89919203/cf417122-bbb1-4e3d-a69c-9faf737fbf96)

### Would you like to work on this issue?

Yes

**Comment by Balastrong** [comment]
Fixed with #91
