### ISSUE TITLE
Broken layout if PR title is too long

### ISSUE THREAD

**Issue by theflucs** [DevLeonardoCommunity/github-stats#93]
### Describe your issue

If PR title is too long the icon is cut

### Steps to reproduce

1. Go to page /stats
2. You're able to see the issue if a PR title is quite long

### What was the expected result?

I expect the layout to stay consistent regardless of the content.

### Put here any screenshots or videos (optional)

![Screenshot 2024-01-18 at 14 05 15](https://github.com/DevLeonardoCommunity/github-stats/assets/89919203/2bb74b32-74f8-42ef-abf1-33474346f11f)

### Would you like to work on this issue?

Yes

**Comment by theflucs** [comment]
I see 2 options:

1. show the 3 dots to indicate that the string continues
2. go to new line without breaking the layout

I would go for the first option, but @Balastrong tell me what you prefer

**Comment by Balastrong** [comment]
I'd say first option but if you hover with the mouse a tooltip shows the full name. What do you think?

**Comment by theflucs** [comment]
I couldn't see any tooltip hovering the pr title. Using the Daisy UI tooltip was breaking the layout, so I just added an `a title` attribute for accessibility and clarity.

**Comment by Balastrong** [comment]
That makes sense, thanks you!

I created a new issue #95 if someone wants to pick it up to specifically work on the tooltip :)
