### ISSUE TITLE
Broken responsive layout in stats page

### ISSUE THREAD

**Issue by theflucs** [DevLeonardoCommunity/github-stats#97]
### Describe your issue

In some cases, I find the layout breaking when resizing the screen.

### Steps to reproduce

Go to page stats and find a card with a long repo title. Resize the screen and, at around 1000px, the totalCount pill starts to overlap the repo title:
![Screenshot 2024-01-27 at 09 43 07](https://github.com/DevLeonardoCommunity/github-stats/assets/89919203/8fd26a9e-e870-42d6-8613-71d30e3b848b)
The size at which it starts breaking depends on how long the title is.

When resizing, at around 860px, the card overflows its container **when more than one card is displayed**:
<img width="178" alt="Screenshot 2024-01-27 at 09 44 07" src="https://github.com/DevLeonardoCommunity/github-stats/assets/89919203/75ad6f50-8f7e-4a6e-a1cb-ead38eedce17">
It doesn't happen with only one card displayed.

### What was the expected result?

I expect the layout to be correctly responsive and the content to always be clearly visible.

### Would you like to work on this issue?

Yes

**Comment by Balastrong** [comment]
Something was already done in #89 to fix a vertical scrollbar but it seems there's more to be fixed :D

Thanks for reporting it and feel free to submit a PR :)
